CREATE TABLE IF NOT EXISTS Delivery (
    DeliveryId BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DriverId BIGINT(20),
    ClientId BIGINT(20) NOT NULL,
    SupplierId BIGINT(20) NOT NULL,
    DeliveryDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL CHECK (Status IN ('Pending', 'In Transit', 'Delivered', 'Cancelled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DriverId) REFERENCES DeliveryDriver(Id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ClientId) REFERENCES Client(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SupplierId) REFERENCES Supplier(Id) ON DELETE CASCADE ON UPDATE CASCADE
);
